### ISSUE TITLE
Crashes with GNOME 3.20 under wayland session

### ISSUE THREAD

**Issue by bigon** [Keruspe/GPaste#150]
Hi,

I'm using debian unstable with gnome-shell running as a wayland compositor and the gpaste-daemon is crashing quite often:

```gdb
#0  0x00007fecba34ad43 in g_paste_daemon_dbus_method_call (priv=<optimized out>, parameters=0xa804f2f3a4035a00) at src/libgpaste/daemon/gpaste-daemon.c:666
#1  0x00007fecba34ad43 in g_paste_daemon_dbus_method_call (connection=<optimized out>, sender=sender@entry=0x7feca4008e80 ":1.165", object_path=object_path@entry=0x7feca4008490 "/org/gnome/GPaste", interface_name=interface_name@entry=0x7feca400a230 "org.gnome.GPaste1", method_name=method_name@entry=0x7feca400a410 "Search", parameters=parameters@entry=0x7feca4009d50, invocation=0x15a5eb0 [GDBusMethodInvocation], user_data=0x16f2970) at src/libgpaste/daemon/gpaste-daemon.c:886
#2  0x00007fecb94b703c in call_in_idle_cb (user_data=0x15a5eb0) at /build/glib2.0-2CrUwg/glib2.0-2.48.0/./gio/gdbusconnection.c:4832
#3  0x00007fecb8ec7fea in g_main_context_dispatch (context=0x1461f30) at /build/glib2.0-2CrUwg/glib2.0-2.48.0/./glib/gmain.c:3154
#4  0x00007fecb8ec7fea in g_main_context_dispatch (context=context@entry=0x1461f30) at /build/glib2.0-2CrUwg/glib2.0-2.48.0/./glib/gmain.c:3769
#5  0x00007fecb8ec8390 in g_main_context_iterate (context=context@entry=0x1461f30, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at /build/glib2.0-2CrUwg/glib2.0-2.48.0/./glib/gmain.c:3840
#6  0x00007fecb8ec843c in g_main_context_iteration (context=context@entry=0x1461f30, may_block=may_block@entry=1) at /build/glib2.0-2CrUwg/glib2.0-2.48.0/./glib/gmain.c:3901
#7  0x00007fecb948fccd in g_application_run (application=application@entry=0x14671a0 [GtkApplication], argc=argc@entry=1, argv=argv@entry=0x7ffff378a638)
    at /build/glib2.0-2CrUwg/glib2.0-2.48.0/./gio/gapplication.c:2381
#8  0x0000000000401596 in main (argc=1, argv=0x7ffff378a638) at src/daemon/gpaste-daemon.c:161
```

I'm not exactly sure what triggers this

**Comment by Keruspe** [comment]
Hi,

Thanks a lot for the report. This is not actualy wayland specific, I'm pretty sure I found the bug, fix is coming soon and I'll probably make a release once that's fixed
