### ISSUE TITLE
GPaste 3.30.2 no UI display

### ISSUE THREAD

**Issue by Java0x56** [Keruspe/GPaste#347]
I'm in Debian 10 Buster and that's the last version in the repositories, so I installed it and everything seams ok, but when I tried to open the UI with gpaste-client ui nothing... no error message and no UI, the manager is working in terminal just no UI

How can I fix this?, thanks...

**Comment by Keruspe** [comment]
Debian probably puts it in another package ?

**Comment by Java0x56** [comment]
I have used it before and it worked, but today when I reinstalled it, it had no UI, if I run "gpaste-client about" it flashes something on screen the immediately closes

**Comment by Keruspe** [comment]
Do you get something if you run in a shell "/usr/libexec/gpaste/gpaste-ui" ?

**Comment by Java0x56** [comment]
`bash: /usr/libexec/gpaste/gpaste-ui: No such file or directory`

**Comment by Keruspe** [comment]
So either you're missing a package or debian installs this somewhere else. I'm not familiar enough with debian to help further

**Comment by Java0x56** [comment]
Thanks, I'll keep trying to make it work...

**Comment by Java0x56** [comment]
> Do you get something if you run in a shell "/usr/libexec/gpaste/gpaste-ui" ?

I found it in `/usr/lib/x86_64-linux-gnu/gpaste/gpaste-ui` but when run I get `Segmentation fault`

**Comment by Keruspe** [comment]
Can you run it with gdb?

**Comment by Java0x56** [comment]
`(gdb) run`
`Starting program: /usr/bin/gpaste-client `
`[Thread debugging using libthread_db enabled]`
`Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".`
`[New Thread 0x7ffff4f42700 (LWP 13530)]`
`[New Thread 0x7fffeffff700 (LWP 13531)]`
`[Thread 0x7ffff4f42700 (LWP 13530) exited]`
`[Thread 0x7ffff4f43f00 (LWP 13526) exited]`
`[Inferior 1 (process 13526) exited normally]`
`(gdb) run ui`
`Starting program: /usr/bin/gpaste-client ui`
`[Thread debugging using libthread_db enabled]`
`Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".`
`[New Thread 0x7ffff4f42700 (LWP 13533)]`
`[New Thread 0x7fffeffff700 (LWP 13534)]`
`[Thread 0x7fffeffff700 (LWP 13534) exited]`
`[Thread 0x7ffff4f43f00 (LWP 13532) exited]`
`[Inferior 1 (process 13532) exited normally]`

**Comment by Keruspe** [comment]
I meant the one that segfaults. Also after the run, you need to type "bt" to gather a backtrace

**Comment by Keruspe** [comment]
Might be the same as #341

**Comment by Java0x56** [comment]
> I meant the one that segfaults. Also after the run, you need to type "bt" to gather a backtrace

`Starting program: /usr/lib/x86_64-linux-gnu/gpaste/gpaste-ui `
`[Thread debugging using libthread_db enabled]`
`Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".`
`[New Thread 0x7ffff4f42700 (LWP 2290)]`
`[New Thread 0x7fffeffff700 (LWP 2291)]`
`[New Thread 0x7fffef7fe700 (LWP 2292)]`
`[New Thread 0x7fffeeffd700 (LWP 2293)]`
` `
`Thread 1 "gpaste-ui" received signal SIGSEGV, Segmentation fault.`
`0x00007ffff7fa0f15 in ?? () from /lib/x86_64-linux-gnu/libgpaste.so.11`
`(gdb) bt`
`#0  0x00007ffff7fa0f15 in ?? () from /lib/x86_64-linux-gnu/libgpaste.so.11`
`#1  0x00007ffff775f799 in ?? () from /lib/x86_64-linux-gnu/libgio-2.0.so.0`
`#2  0x00007ffff7760216 in ?? () from /lib/x86_64-linux-gnu/libgio-2.0.so.0`
`#3  0x00007ffff77c1089 in ?? () from /lib/x86_64-linux-gnu/libgio-2.0.so.0`
`#4  0x00007ffff775f799 in ?? () from /lib/x86_64-linux-gnu/libgio-2.0.so.0`
`#5  0x00007ffff7760216 in ?? () from /lib/x86_64-linux-gnu/libgio-2.0.so.0`
`#6  0x00007ffff77b5cb1 in ?? () from /lib/x86_64-linux-gnu/libgio-2.0.so.0`
`#7  0x00007ffff775f799 in ?? () from /lib/x86_64-linux-gnu/libgio-2.0.so.0`
`#8  0x00007ffff775f7d9 in ?? () from /lib/x86_64-linux-gnu/libgio-2.0.so.0`
`#9  0x00007ffff7597dd8 in g_main_context_dispatch ()`
`   from /lib/x86_64-linux-gnu/libglib-2.0.so.0`
`#10 0x00007ffff75981c8 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0`
`#11 0x00007ffff759825c in g_main_context_iteration ()`
`   from /lib/x86_64-linux-gnu/libglib-2.0.so.0`
`#12 0x00007ffff778aa2d in g_application_run ()`
`   from /lib/x86_64-linux-gnu/libgio-2.0.so.0`
`#13 0x000055555555640c in ?? ()`
`#14 0x00007ffff73ad09b in __libc_start_main (main=0x5555555562b0, argc=1, `
`    argv=0x7fffffffe418, init=<optimized out>, fini=<optimized out>, `
`    rtld_fini=<optimized out>, stack_end=0x7fffffffe408)`
`    at ../csu/libc-start.c:308`
`#15 0x000055555555665a in ?? ()`

**Comment by Java0x56** [comment]
> Might be the same as #341

Ok, where can i find the settings?, is there a file I can edit? because the program doesn't run, to test this...

**Comment by attila-lendvai** [comment]
i'm trying to package gpaste for Guix, and i'm also seeing a sigsegv of gpaste-ui. some window seems to open up in the Alt+Tab list, but nothing shows onscreen.

```
$ gdb /gnu/store/594nc6ligl7m6g5ksib059x7n0f313fb-gpaste-3.34.4/libexec/gpaste/gpaste-ui 
Reading symbols from /gnu/store/594nc6ligl7m6g5ksib059x7n0f313fb-gpaste-3.34.4/libexec/gpaste/gpaste-ui...
(No debugging symbols found in /gnu/store/594nc6ligl7m6g5ksib059x7n0f313fb-gpaste-3.34.4/libexec/gpaste/gpaste-ui)
(gdb) r
Starting program: /gnu/store/594nc6ligl7m6g5ksib059x7n0f313fb-gpaste-3.34.4/libexec/gpaste/gpaste-ui 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/gnu/store/fa6wj5bxkj5ll1d7292a70knmyl7a0cr-glibc-2.31/lib/libthread_db.so.1".
[New Thread 0x7ffff64e0700 (LWP 6057)]
[New Thread 0x7ffff5cdf700 (LWP 6058)]
[New Thread 0x7ffff4c1c700 (LWP 6059)]
[New Thread 0x7fffe7fff700 (LWP 6060)]

Thread 1 "gpaste-ui" received signal SIGSEGV, Segmentation fault.
0x00007ffff7fabf85 in on_histories_ready () from /gnu/store/594nc6ligl7m6g5ksib059x7n0f313fb-gpaste-3.34.4/lib/libgpaste.so.11
(gdb) back
#0  0x00007ffff7fabf85 in on_histories_ready () from /gnu/store/594nc6ligl7m6g5ksib059x7n0f313fb-gpaste-3.34.4/lib/libgpaste.so.11
#1  0x00007ffff76ce489 in g_task_return_now () from /gnu/store/3374zddwfb0m8711k2jrvhwr1s2fkvq3-glib-2.62.6/lib/libgio-2.0.so.0
#2  0x00007ffff76cef93 in g_task_return.part () from /gnu/store/3374zddwfb0m8711k2jrvhwr1s2fkvq3-glib-2.62.6/lib/libgio-2.0.so.0
#3  0x00007ffff772f065 in reply_cb () from /gnu/store/3374zddwfb0m8711k2jrvhwr1s2fkvq3-glib-2.62.6/lib/libgio-2.0.so.0
#4  0x00007ffff76ce489 in g_task_return_now () from /gnu/store/3374zddwfb0m8711k2jrvhwr1s2fkvq3-glib-2.62.6/lib/libgio-2.0.so.0
#5  0x00007ffff76cef93 in g_task_return.part () from /gnu/store/3374zddwfb0m8711k2jrvhwr1s2fkvq3-glib-2.62.6/lib/libgio-2.0.so.0
#6  0x00007ffff7723fe2 in g_dbus_connection_call_done () from /gnu/store/3374zddwfb0m8711k2jrvhwr1s2fkvq3-glib-2.62.6/lib/libgio-2.0.so.0
#7  0x00007ffff76ce489 in g_task_return_now () from /gnu/store/3374zddwfb0m8711k2jrvhwr1s2fkvq3-glib-2.62.6/lib/libgio-2.0.so.0
#8  0x00007ffff76ce4c9 in complete_in_idle_cb () from /gnu/store/3374zddwfb0m8711k2jrvhwr1s2fkvq3-glib-2.62.6/lib/libgio-2.0.so.0
#9  0x00007ffff74eef14 in g_main_context_dispatch () from /gnu/store/3374zddwfb0m8711k2jrvhwr1s2fkvq3-glib-2.62.6/lib/libglib-2.0.so.0
#10 0x00007ffff74ef288 in g_main_context_iterate.isra () from /gnu/store/3374zddwfb0m8711k2jrvhwr1s2fkvq3-glib-2.62.6/lib/libglib-2.0.so.0
#11 0x00007ffff74ef30c in g_main_context_iteration () from /gnu/store/3374zddwfb0m8711k2jrvhwr1s2fkvq3-glib-2.62.6/lib/libglib-2.0.so.0
#12 0x00007ffff76f9a3d in g_application_run () from /gnu/store/3374zddwfb0m8711k2jrvhwr1s2fkvq3-glib-2.62.6/lib/libgio-2.0.so.0
#13 0x00000000004023b9 in main ()
(gdb) 
```

note that i'm running an older version of gpaste, because:

```
$ gnome-shell --version
GNOME Shell 3.34.5
```

**Comment by Keruspe** [comment]
This whole tool has now been rewritten in gtk4
